name: 'Build Number Generator'
description: 'Generate sequential build numbers for workflow runs'
author: 'Einar Egilsson'
runs:
  using: 'node12'
  main: 'main.js'
inputs:
  token:
    description: 'GitHub Token to create and delete refs (GITHUB_TOKEN)'
    required: true
  repository:
    description: 'Id of the repository being worked on (GITHUB_REPOSITORY)'
    required:  true
  sha:
    description: 'Sha of the current commit that triggered the build (GITHUB_SHA)'
    required:  true
    
outputs:
  build_number:
    description: 'Generated build number'
  
branding:
  icon: 'hash'  
  color: 'green'
