name: 'Build Number Generator'
description: 'Generate sequential build numbers for workflow runs'
author: 'Einar Egilsson'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'hash'  
  color: 'green'